package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EdoTyran
 */
public class Admin extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Employee
     */
    public Admin() {
        super("Lost Baggage");
        setSize(1300,650);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Name = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AdminHome = new javax.swing.JPanel();
        helpTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Backgroundlabel = new javax.swing.JLabel();
        AdminEdit = new javax.swing.JPanel();
        corendonTitleEdit = new javax.swing.JLabel();
        zipEdit = new javax.swing.JLabel();
        countryEdit = new javax.swing.JLabel();
        addressEdit = new javax.swing.JLabel();
        cityEdit = new javax.swing.JLabel();
        nameEdit = new javax.swing.JLabel();
        emailEdit = new javax.swing.JLabel();
        addressFieldEdit = new javax.swing.JTextField();
        cityFieldEdit = new javax.swing.JTextField();
        zipFieldEdit = new javax.swing.JTextField();
        emailFieldEdit = new javax.swing.JTextField();
        nameFieldEdit = new javax.swing.JTextField();
        countryFieldEdit = new javax.swing.JTextField();
        accountInfoTitleEdit = new javax.swing.JLabel();
        repeatwwFieldEdit = new javax.swing.JTextField();
        accountypeEdit = new javax.swing.JLabel();
        repeatwwEdit = new javax.swing.JLabel();
        newwwEdit = new javax.swing.JLabel();
        newwwFieldEdit = new javax.swing.JTextField();
        oldwwFieldEdit = new javax.swing.JTextField();
        oldwwEdit = new javax.swing.JLabel();
        newusernameEdit = new javax.swing.JLabel();
        newusernameFieldEdit = new javax.swing.JTextField();
        accountEdit = new javax.swing.JLabel();
        PersonalInfoTitleEdit = new javax.swing.JLabel();
        accountDropboxEdit = new javax.swing.JComboBox();
        accounttypeDropboxEdit = new javax.swing.JComboBox();
        background = new javax.swing.JLabel();
        AdminCreate = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        AdminDelete = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        AdminHelp = new javax.swing.JPanel();
        helpTitle6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        homeButton1 = new javax.swing.JLabel();
        editButton = new javax.swing.JLabel();
        createButton = new javax.swing.JLabel();
        deleteButton = new javax.swing.JLabel();
        helpButton = new javax.swing.JLabel();
        logoutKnop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Logged in as:");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 40));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Employee ID:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel1.setLayout(new java.awt.BorderLayout());

        AdminHome.setBackground(new java.awt.Color(153, 51, 51));
        AdminHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        AdminHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpTitle1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        helpTitle1.setText("Welcome Admin,");
        AdminHome.add(helpTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name: ");
        AdminHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Account type:");
        AdminHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 110, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yassinee\\Downloads\\CorendonLogo.png")); // NOI18N
        AdminHome.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 200, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID:");
        AdminHome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 20));

        jTextField1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField1.setText("Example: John");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        AdminHome.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField2.setText("Example: Manager");
        AdminHome.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 100, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField3.setText("Example: 3");
        AdminHome.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 100, -1));

        Backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        Backgroundlabel.setToolTipText("");
        Backgroundlabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminHome.add(Backgroundlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        AdminEdit.setBackground(new java.awt.Color(153, 51, 51));
        AdminEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonTitleEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonTitleEdit.setText("jLabel11");
        AdminEdit.add(corendonTitleEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        zipEdit.setText("Zip/Postal code   :");
        AdminEdit.add(zipEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, 20));

        countryEdit.setText("Country    :");
        AdminEdit.add(countryEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        addressEdit.setText("Address   :");
        AdminEdit.add(addressEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        cityEdit.setText("City     :");
        AdminEdit.add(cityEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        nameEdit.setText("Name   :");
        AdminEdit.add(nameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        emailEdit.setText("Email     :");
        AdminEdit.add(emailEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        addressFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressFieldEdit.setText("Example: Egidiusstraat");
        addressFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldEditActionPerformed(evt);
            }
        });
        AdminEdit.add(addressFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        cityFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityFieldEdit.setText("Example: Amsterdam");
        AdminEdit.add(cityFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        zipFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        zipFieldEdit.setText("Example: 1055GK");
        AdminEdit.add(zipFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        emailFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailFieldEdit.setText("Example: John@corendon.com");
        AdminEdit.add(emailFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        nameFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameFieldEdit.setText("example: john");
        AdminEdit.add(nameFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        countryFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryFieldEdit.setText("Example: The Netherlands");
        AdminEdit.add(countryFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        accountInfoTitleEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountInfoTitleEdit.setText("Account information:");
        AdminEdit.add(accountInfoTitleEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        repeatwwFieldEdit.setText("***********");
        AdminEdit.add(repeatwwFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 240, -1));

        accountypeEdit.setText("Account type     :");
        AdminEdit.add(accountypeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 100, -1));

        repeatwwEdit.setText(" repeat password  :");
        AdminEdit.add(repeatwwEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 20));

        newwwEdit.setText("New Password   :");
        AdminEdit.add(newwwEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 20));

        newwwFieldEdit.setText("***********");
        AdminEdit.add(newwwFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 240, -1));

        oldwwFieldEdit.setText("***********");
        AdminEdit.add(oldwwFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, -1));

        oldwwEdit.setText("Old Password  :");
        AdminEdit.add(oldwwEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        newusernameEdit.setText("New Username :");
        AdminEdit.add(newusernameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 20));

        newusernameFieldEdit.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        newusernameFieldEdit.setText("Example: Administrator1988");
        AdminEdit.add(newusernameFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, -1));

        accountEdit.setText("Account:");
        AdminEdit.add(accountEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        PersonalInfoTitleEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PersonalInfoTitleEdit.setText("Personal information:");
        AdminEdit.add(PersonalInfoTitleEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        accountDropboxEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Account1", "Account1", "Account1", "Account1", "Account1", "Account1" }));
        accountDropboxEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountDropboxEditActionPerformed(evt);
            }
        });
        AdminEdit.add(accountDropboxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 240, -1));

        accounttypeDropboxEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Administrator", "Employee" }));
        AdminEdit.add(accounttypeDropboxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 240, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        background.setToolTipText("");
        background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminEdit.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        AdminHome.add(AdminEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminCreate.setBackground(new java.awt.Color(153, 51, 51));
        AdminCreate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel31.setText("jLabel11");
        AdminCreate.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel32.setText("Zip/Postal code   :");
        AdminCreate.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, 20));

        jLabel33.setText("Country    :");
        AdminCreate.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        jLabel34.setText("Address   :");
        AdminCreate.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        jLabel35.setText("City     :");
        AdminCreate.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel36.setText("Name   :");
        AdminCreate.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        jLabel37.setText("Email     :");
        AdminCreate.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jTextField18.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField18.setText("Example: Egidiusstraat");
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        AdminCreate.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        jTextField19.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField19.setText("Example: Amsterdam");
        jTextField19.setToolTipText("");
        AdminCreate.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        jTextField20.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField20.setText("Example: 1055GK");
        AdminCreate.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        jTextField21.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField21.setText("Example: John@corendon.com");
        AdminCreate.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        jTextField22.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField22.setText("example: john");
        AdminCreate.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        jTextField23.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField23.setText("Example: The Netherlands");
        AdminCreate.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Account information:");
        AdminCreate.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel39.setText("Account type     :");
        AdminCreate.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, -1));

        jLabel40.setText(" repeat password  :");
        AdminCreate.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 20));

        jLabel41.setText("New Password   :");
        AdminCreate.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 20));

        jTextField26.setText("**********");
        AdminCreate.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 240, -1));

        jTextField27.setText("**********");
        AdminCreate.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, -1));

        jLabel43.setText("New Username :");
        AdminCreate.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 20));

        jTextField28.setText("Example: Adminstrator1981");
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        AdminCreate.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Personal information:");
        AdminCreate.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Administrator", "Employee" }));
        AdminCreate.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel9.setToolTipText("");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminCreate.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        AdminHome.add(AdminCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminDelete.setBackground(new java.awt.Color(153, 51, 51));
        AdminDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel42.setText("jLabel11");
        AdminDelete.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel44.setText("Zip/Postal code   :");
        AdminDelete.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, 20));

        jLabel46.setText("Country    :");
        AdminDelete.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 70, 20));

        jLabel47.setText("Address   :");
        AdminDelete.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        jLabel48.setText("City     :");
        AdminDelete.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel49.setText("Name   :");
        AdminDelete.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        jLabel50.setText("Email     :");
        AdminDelete.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jTextField24.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField24.setText("Example: Egidiusstraat");
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        AdminDelete.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        jTextField25.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField25.setText("Example: Amsterdam");
        jTextField25.setToolTipText("");
        AdminDelete.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        jTextField29.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField29.setText("Example: 1055GK");
        AdminDelete.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        jTextField30.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField30.setText("Example: John@corendon.com");
        AdminDelete.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        jTextField31.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField31.setText("example: john");
        AdminDelete.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        jTextField32.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField32.setText("Example: The Netherlands");
        AdminDelete.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setText("Account information:");
        AdminDelete.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel52.setText("Account type     :");
        AdminDelete.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, -1));

        jLabel53.setText(" repeat password  :");
        AdminDelete.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 20));

        jLabel54.setText("New Password   :");
        AdminDelete.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 20));

        jTextField33.setText("**********");
        AdminDelete.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 240, -1));

        jTextField34.setText("**********");
        AdminDelete.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, -1));

        jLabel55.setText("New Username :");
        AdminDelete.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 20));

        jTextField35.setText("Example: Adminstrator1981");
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        AdminDelete.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Personal information:");
        AdminDelete.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Administrator", "Employee" }));
        AdminDelete.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel10.setToolTipText("");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminDelete.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        AdminHome.add(AdminDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AdminHelp.setBackground(new java.awt.Color(153, 51, 51));
        AdminHelp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        AdminHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpTitle6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        helpTitle6.setText("Welkom Manager,");
        AdminHelp.add(helpTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminHelp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        AdminHome.add(AdminHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(AdminHome, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 910, 460));

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        homeButton1.setBackground(new java.awt.Color(255, 255, 255));
        homeButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton1.setText("Home");
        homeButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton1.setOpaque(true);
        homeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButton1MouseExited(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editButton.setText("Edit account");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setOpaque(true);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(255, 255, 255));
        createButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createButton.setText("Create account");
        createButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButton.setOpaque(true);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createButtonMouseExited(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteButton.setText("Delete account");
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setOpaque(true);
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.setOpaque(true);
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addComponent(homeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 144, Short.MAX_VALUE))
        );

        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 178, 410));

        logoutKnop.setBackground(new java.awt.Color(147, 51, 51));
        logoutKnop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutKnop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutKnop.setText("LOGOUT");
        logoutKnop.setOpaque(true);
        logoutKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutKnopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutKnopMouseExited(evt);
            }
        });
        getContentPane().add(logoutKnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 89, 90, 33));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void homeButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_homeButton1MouseClicked

    private void homeButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseEntered
        homeButton1.setBackground(Color.lightGray);
    }//GEN-LAST:event_homeButton1MouseEntered

    private void homeButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseExited
        homeButton1.setBackground(Color.white);
    }//GEN-LAST:event_homeButton1MouseExited

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminEdit);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_editButtonMouseClicked

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        editButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        editButton.setBackground(Color.white);
    }//GEN-LAST:event_editButtonMouseExited

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminCreate);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_createButtonMouseClicked

    private void createButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseEntered
        createButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_createButtonMouseEntered

    private void createButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseExited
        createButton.setBackground(Color.white);
    }//GEN-LAST:event_createButtonMouseExited

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminDelete);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        deleteButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        deleteButton.setBackground(Color.white);
    }//GEN-LAST:event_deleteButtonMouseExited

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminHelp);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_helpButtonMouseClicked

    private void helpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseEntered
        helpButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_helpButtonMouseEntered

    private void helpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseExited
        helpButton.setBackground(Color.white);
    }//GEN-LAST:event_helpButtonMouseExited

    private void addressFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldEditActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void accountDropboxEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountDropboxEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountDropboxEditActionPerformed

    private void logoutKnopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseEntered
        logoutKnop.setBackground(new java.awt.Color(224,90,90));
    }//GEN-LAST:event_logoutKnopMouseEntered

    private void logoutKnopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseExited
        logoutKnop.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_logoutKnopMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCreate;
    private javax.swing.JPanel AdminDelete;
    private javax.swing.JPanel AdminEdit;
    private javax.swing.JPanel AdminHelp;
    private javax.swing.JPanel AdminHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Backgroundlabel;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel PersonalInfoTitleEdit;
    private javax.swing.JComboBox accountDropboxEdit;
    private javax.swing.JLabel accountEdit;
    private javax.swing.JLabel accountInfoTitleEdit;
    private javax.swing.JComboBox accounttypeDropboxEdit;
    private javax.swing.JLabel accountypeEdit;
    private javax.swing.JLabel addressEdit;
    private javax.swing.JTextField addressFieldEdit;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cityEdit;
    private javax.swing.JTextField cityFieldEdit;
    private javax.swing.JLabel corendonTitleEdit;
    private javax.swing.JLabel countryEdit;
    private javax.swing.JTextField countryFieldEdit;
    private javax.swing.JLabel createButton;
    private javax.swing.JLabel deleteButton;
    private javax.swing.JLabel editButton;
    private javax.swing.JLabel emailEdit;
    private javax.swing.JTextField emailFieldEdit;
    private javax.swing.JLabel helpButton;
    private javax.swing.JLabel helpTitle1;
    private javax.swing.JLabel helpTitle6;
    private javax.swing.JLabel homeButton1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JLabel logoutKnop;
    private javax.swing.JPanel menu1;
    private javax.swing.JLabel nameEdit;
    private javax.swing.JTextField nameFieldEdit;
    private javax.swing.JLabel newusernameEdit;
    private javax.swing.JTextField newusernameFieldEdit;
    private javax.swing.JLabel newwwEdit;
    private javax.swing.JTextField newwwFieldEdit;
    private javax.swing.JLabel oldwwEdit;
    private javax.swing.JTextField oldwwFieldEdit;
    private javax.swing.JLabel repeatwwEdit;
    private javax.swing.JTextField repeatwwFieldEdit;
    private javax.swing.JLabel zipEdit;
    private javax.swing.JTextField zipFieldEdit;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
