package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EdoTyran
 */
public class Employee extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Name = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        employeeAddBaggage = new javax.swing.JPanel();
        addBaggageTitle = new javax.swing.JLabel();
        employeeSearch = new javax.swing.JPanel();
        SearchTitle = new javax.swing.JLabel();
        employeeHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        employeeSubmitRequest = new javax.swing.JPanel();
        submitRequestTitle = new javax.swing.JLabel();
        employeeHelp = new javax.swing.JPanel();
        helpTitle = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        helpButtom = new javax.swing.JToggleButton();
        addBaggageButtom = new javax.swing.JToggleButton();
        submitRequestButtom = new javax.swing.JToggleButton();
        employeeHomeButton = new javax.swing.JButton();
        employeeSearchButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Logged in as:");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 40));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Employee ID:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, 40));

        Logout.setBackground(new java.awt.Color(151, 51, 51));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("blablabla");
        Logout.setBorder(null);
        Logout.setBorderPainted(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, 70, 30));

        jPanel1.setBackground(new java.awt.Color(153, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeAddBaggage.setBackground(new java.awt.Color(153, 51, 51));
        employeeAddBaggage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBaggageTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addBaggageTitle.setText("Add Baggage");
        employeeAddBaggage.add(addBaggageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jPanel1.add(employeeAddBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 470));

        employeeSearch.setBackground(new java.awt.Color(153, 51, 51));
        employeeSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SearchTitle.setText("Search");
        employeeSearch.add(SearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jPanel1.add(employeeSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 470));

        employeeHome.setBackground(new java.awt.Color(153, 51, 51));
        employeeHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Home");
        employeeHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jPanel1.add(employeeHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        employeeSubmitRequest.setBackground(new java.awt.Color(153, 51, 51));
        employeeSubmitRequest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitRequestTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submitRequestTitle.setText("Submit Request");
        employeeSubmitRequest.add(submitRequestTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jPanel1.add(employeeSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 470));

        employeeHelp.setBackground(new java.awt.Color(153, 51, 51));
        employeeHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpTitle.setText("Help");
        employeeHelp.add(helpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jPanel1.add(employeeHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 990, 500));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        helpButtom.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        helpButtom.setText("Help");
        helpButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtomActionPerformed(evt);
            }
        });

        addBaggageButtom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addBaggageButtom.setText("Add baggage");
        addBaggageButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBaggageButtomActionPerformed(evt);
            }
        });

        submitRequestButtom.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        submitRequestButtom.setText("Submit Request");
        submitRequestButtom.setToolTipText("DIT IS EEN HOME KNOPP!!!!!!!!!!!!!!!!!!!!!!!!!!");
        submitRequestButtom.setAlignmentX(1.0F);
        submitRequestButtom.setAlignmentY(0.0F);
        submitRequestButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRequestButtomActionPerformed(evt);
            }
        });

        employeeHomeButton.setText("Home");
        employeeHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeHomeButtonMouseClicked(evt);
            }
        });
        employeeHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeHomeButtonActionPerformed(evt);
            }
        });

        employeeSearchButton.setText("Search");
        employeeSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeSearchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBaggageButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitRequestButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helpButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(employeeHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(employeeSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addBaggageButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(submitRequestButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(helpButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, 410));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void helpButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtomActionPerformed

    private void addBaggageButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBaggageButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBaggageButtomActionPerformed

    private void submitRequestButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRequestButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitRequestButtomActionPerformed

    private void employeeHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeHomeButtonActionPerformed
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(employeeHome);
        jPanel1.revalidate();
    }//GEN-LAST:event_employeeHomeButtonActionPerformed

    private void employeeHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeHomeButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(employeeHome);
        jPanel1.revalidate();
    }//GEN-LAST:event_employeeHomeButtonMouseClicked

    private void employeeSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeSearchButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(employeeSearch);
        jPanel1.revalidate();
    }//GEN-LAST:event_employeeSearchButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel ID;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel SearchTitle;
    private javax.swing.JToggleButton addBaggageButtom;
    private javax.swing.JLabel addBaggageTitle;
    private javax.swing.JPanel employeeAddBaggage;
    private javax.swing.JPanel employeeHelp;
    private javax.swing.JPanel employeeHome;
    private javax.swing.JButton employeeHomeButton;
    private javax.swing.JPanel employeeSearch;
    private javax.swing.JButton employeeSearchButton;
    private javax.swing.JPanel employeeSubmitRequest;
    private javax.swing.JToggleButton helpButtom;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JToggleButton submitRequestButtom;
    private javax.swing.JLabel submitRequestTitle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
