package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EdoTyran
 */
public class Manager extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Employee
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Name = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ManagerHome = new javax.swing.JPanel();
        helpTitle1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        searchButton = new javax.swing.JLabel();
        StatusButton = new javax.swing.JLabel();
        LogfilesButton = new javax.swing.JLabel();
        Graphbutton = new javax.swing.JLabel();
        helpButton1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        ManagerSearch = new javax.swing.JPanel();
        addBaggageTitle = new javax.swing.JLabel();
        Managerstatus = new javax.swing.JPanel();
        SearchTitle = new javax.swing.JLabel();
        ManagerLogfiles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Managerhelp = new javax.swing.JPanel();
        submitRequestTitle = new javax.swing.JLabel();
        ManagerGraphs = new javax.swing.JPanel();
        helpTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Logged in as:");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 40));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Employee ID:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, 40));

        Logout.setBackground(new java.awt.Color(151, 51, 51));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("blablabla");
        Logout.setBorder(null);
        Logout.setBorderPainted(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, 70, 30));

        jPanel1.setBackground(new java.awt.Color(153, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        ManagerHome.setBackground(new java.awt.Color(153, 51, 51));
        ManagerHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpTitle1.setText("Welkom Manager,");
        ManagerHome.add(helpTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jPanel1.add(ManagerHome, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 890, 450));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setOpaque(true);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setOpaque(true);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });

        StatusButton.setBackground(new java.awt.Color(255, 255, 255));
        StatusButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StatusButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusButton.setText("Status");
        StatusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StatusButton.setOpaque(true);
        StatusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatusButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StatusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StatusButtonMouseExited(evt);
            }
        });

        LogfilesButton.setBackground(new java.awt.Color(255, 255, 255));
        LogfilesButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogfilesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogfilesButton.setText("Log files");
        LogfilesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogfilesButton.setOpaque(true);
        LogfilesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogfilesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogfilesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogfilesButtonMouseExited(evt);
            }
        });

        Graphbutton.setBackground(new java.awt.Color(255, 255, 255));
        Graphbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Graphbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Graphbutton.setText("Graphs");
        Graphbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Graphbutton.setOpaque(true);
        Graphbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GraphbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GraphbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GraphbuttonMouseExited(evt);
            }
        });

        helpButton1.setBackground(new java.awt.Color(255, 255, 255));
        helpButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helpButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpButton1.setText("Help");
        helpButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton1.setOpaque(true);
        helpButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButton1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(StatusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogfilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Graphbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(StatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LogfilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Graphbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 178, 410));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        ManagerSearch.setBackground(new java.awt.Color(153, 51, 51));
        ManagerSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBaggageTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addBaggageTitle.setText("Search");
        ManagerSearch.add(addBaggageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        getContentPane().add(ManagerSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 950, 320));

        Managerstatus.setBackground(new java.awt.Color(153, 51, 51));
        Managerstatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SearchTitle.setText("Search");
        Managerstatus.add(SearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        getContentPane().add(Managerstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 470));

        ManagerLogfiles.setBackground(new java.awt.Color(153, 51, 51));
        ManagerLogfiles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manager Logfiles");
        ManagerLogfiles.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        getContentPane().add(ManagerLogfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        Managerhelp.setBackground(new java.awt.Color(153, 51, 51));
        Managerhelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitRequestTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submitRequestTitle.setText("Help");
        Managerhelp.add(submitRequestTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        getContentPane().add(Managerhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 470));

        ManagerGraphs.setBackground(new java.awt.Color(153, 51, 51));
        ManagerGraphs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpTitle.setText("Graphs");
        ManagerGraphs.add(helpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        getContentPane().add(ManagerGraphs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 470));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setBackground(Color.white);
    }//GEN-LAST:event_homeButtonMouseExited

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        searchButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void StatusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseEntered
        StatusButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_StatusButtonMouseEntered

    private void LogfilesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogfilesButtonMouseEntered
        LogfilesButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_LogfilesButtonMouseEntered

    private void GraphbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraphbuttonMouseEntered
        Graphbutton.setBackground(Color.lightGray);
    }//GEN-LAST:event_GraphbuttonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        searchButton.setBackground(Color.white);
    }//GEN-LAST:event_searchButtonMouseExited

    private void StatusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseExited
        StatusButton.setBackground(Color.white);
    }//GEN-LAST:event_StatusButtonMouseExited

    private void LogfilesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogfilesButtonMouseExited
        LogfilesButton.setBackground(Color.white);
    }//GEN-LAST:event_LogfilesButtonMouseExited

    private void GraphbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraphbuttonMouseExited
        Graphbutton.setBackground(Color.white);
    }//GEN-LAST:event_GraphbuttonMouseExited

    private void helpButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseEntered
        helpButton1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_helpButton1MouseEntered

    private void helpButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseExited
        helpButton1.setBackground(Color.white);
    }//GEN-LAST:event_helpButton1MouseExited

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
         jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerSearch);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void StatusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatusButtonMouseClicked
      jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Managerstatus);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_StatusButtonMouseClicked

    private void LogfilesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogfilesButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerLogfiles);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_LogfilesButtonMouseClicked

    private void GraphbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GraphbuttonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManagerGraphs);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_GraphbuttonMouseClicked

    private void helpButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Managerhelp);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_helpButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Graphbutton;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel LogfilesButton;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel ManagerGraphs;
    private javax.swing.JPanel ManagerHome;
    private javax.swing.JPanel ManagerLogfiles;
    private javax.swing.JPanel ManagerSearch;
    private javax.swing.JPanel Managerhelp;
    private javax.swing.JPanel Managerstatus;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel SearchTitle;
    private javax.swing.JLabel StatusButton;
    private javax.swing.JLabel addBaggageTitle;
    private javax.swing.JLabel helpButton1;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JLabel helpTitle1;
    private javax.swing.JLabel homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel searchButton;
    private javax.swing.JLabel submitRequestTitle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
